In [1]:
path_file = "/home/ahmed.bargady/lustre/data_sec-um6p-st-sccs-6sevvl76uja/IDS/ahmed.bargady/datasets/temp/prod/santos_all.csv"

In [2]:
import pandas as pd

/home/ahmed.bargady/.local/lib/python3.8/site-packages/pandas/core/computation/expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED


In [3]:
df = pd.read_csv(path_file, low_memory=False)

In [4]:
df.head(
    
)

,line,content,labels,rules,datetime,timestamp,source,Content,Label
0,0,2022-01-13T14:31:34.934Z intranet-server syste...,NaN,NaN,2022-01-13 14:31:34.934000+00:00,2022-01-13 14:31:34.934,intranet_monitor,<TIMESTAMP> intranet-server system/system.cpu ...,0
1,1,2022-01-13T14:31:43.504Z intranet-server syste...,NaN,NaN,2022-01-13 14:31:43.504000+00:00,2022-01-13 14:31:43.504,intranet_monitor,<TIMESTAMP> intranet-server system/system.cpu ...,0
2,2,2022-01-13T14:32:28.504Z intranet-server syste...,NaN,NaN,2022-01-13 14:32:28.504000+00:00,2022-01-13 14:32:28.504,intranet_monitor,<TIMESTAMP> intranet-server system/system.cpu ...,0
3,3,2022-01-13T14:33:13.504Z intranet-server syste...,NaN,NaN,2022-01-13 14:33:13.504000+00:00,2022-01-13 14:33:13.504,intranet_monitor,<TIMESTAMP> intranet-server system/system.cpu ...,0
4,4,2022-01-13T14:33:58.504Z intranet-server syste...,NaN,NaN,2022-01-13 14:33:58.504000+00:00,2022-01-13 14:33:58.504,intranet_monitor,<TIMESTAMP> intranet-server system/system.cpu ...,0


In [13]:
dfc = df.copy()

In [14]:
dfc.insert(0, 'LineId', None)
dfc['LineId'] = range(1, len(dfc) + 1)
dfc

,LineId,line,content,labels,rules,datetime,timestamp,source,Content,Label
0,1,0,2022-01-13T14:31:34.934Z intranet-server syste...,NaN,NaN,2022-01-13 14:31:34.934000+00:00,2022-01-13 14:31:34.934,intranet_monitor,<TIMESTAMP> intranet-server system/system.cpu ...,0
1,2,1,2022-01-13T14:31:43.504Z intranet-server syste...,NaN,NaN,2022-01-13 14:31:43.504000+00:00,2022-01-13 14:31:43.504,intranet_monitor,<TIMESTAMP> intranet-server system/system.cpu ...,0
2,3,2,2022-01-13T14:32:28.504Z intranet-server syste...,NaN,NaN,2022-01-13 14:32:28.504000+00:00,2022-01-13 14:32:28.504,intranet_monitor,<TIMESTAMP> intranet-server system/system.cpu ...,0
3,4,3,2022-01-13T14:33:13.504Z intranet-server syste...,NaN,NaN,2022-01-13 14:33:13.504000+00:00,2022-01-13 14:33:13.504,intranet_monitor,<TIMESTAMP> intranet-server system/system.cpu ...,0
4,5,4,2022-01-13T14:33:58.504Z intranet-server syste...,NaN,NaN,2022-01-13 14:33:58.504000+00:00,2022-01-13 14:33:58.504,intranet_monitor,<TIMESTAMP> intranet-server system/system.cpu ...,0
...,...,...,...,...,...,...,...,...,...,...
309626,309627,454,2022-01-18T05:40:43.504Z intranet-server syste...,NaN,NaN,2022-01-18 05:40:43.504000+00:00,2022-01-18 05:40:43.504,intranet_monitor,<TIMESTAMP> intranet-server system/system.cpu ...,0
309627,309628,455,2022-01-18T05:41:28.504Z intranet-server syste...,NaN,NaN,2022-01-18 05:41:28.504000+00:00,2022-01-18 05:41:28.504,intranet_monitor,<TIMESTAMP> intranet-server system/system.cpu ...,0
309628,309629,456,2022-01-18T05:42:13.504Z intranet-server syste...,NaN,NaN,2022-01-18 05:42:13.504000+00:00,2022-01-18 05:42:13.504,intranet_monitor,<TIMESTAMP> intranet-server system/system.cpu ...,0
309629,309630,457,2022-01-18T05:42:58.504Z intranet-server syste...,NaN,NaN,2022-01-18 05:42:58.504000+00:00,2022-01-18 05:42:58.504,intranet_monitor,<TIMESTAMP> intranet-server system/system.cpu ...,0


In [ ]:
# sbp.run(["logadu", "parse", file_path, "--parser", "drain"])
!logadu parse /home/ahmed.bargady/lustre/data_sec-um6p-st-sccs-6sevvl76uja/IDS/ahmed.bargady/datasets/temp/prod/santos_all.csv --parser drain

In [2]:
import pandas as pd

In [1]:
_file_path = "/home/ahmed.bargady/lustre/data_sec-um6p-st-sccs-6sevvl76uja/IDS/ahmed.bargady/datasets/temp/prod/drain/shaw_all_structured.csv"

In [3]:
usecols = ['EventId','Label']
df = pd.read_csv(_file_path, usecols=usecols, low_memory=False)

In [4]:
df.head()

,Label,EventId
0,0,b916f507
1,0,b916f507
2,0,b916f507
3,0,b916f507
4,0,b916f507


In [19]:
df.shape

(373866, 2)

In [20]:
codes, uniques = pd.factorize(df['EventId'], sort=True)
len(codes)

373866

In [7]:
uniques

Index(['0056ce95', '011f88b3', '012bf490', '02877adb', '02d62618', '039ff6dd',
       '056a5fe2', '08d1f5f6', '09c93c67', '0c3b33b9',
       ...
       'f5095f7d', 'f65f117b', 'f701d526', 'f8727b21', 'f9eede1b', 'fab02453',
       'fc227a61', 'fd85201c', 'fda02add', 'fdea319d'],
      dtype='object', length=283)

In [8]:
vocab_size = len(uniques)
vocab_size

283

In [9]:
import numpy as np

In [11]:
labels = df['Label'].to_numpy(dtype=np.int8)
labels

array([0, 0, 0, ..., 0, 0, 0], dtype=int8)

In [28]:
windows = np.lib.stride_tricks.sliding_window_view(codes, 5)
windows.shape

(373862, 5)

In [29]:
windows[:5]

array([[207, 207, 207, 207, 207],
       [207, 207, 207, 207, 207],
       [207, 207, 207, 207, 207],
       [207, 207, 207, 207, 207],
       [207, 207, 207, 207, 207]])

In [32]:
windows = windows[:-1]

In [33]:
windows.shape

(373861, 5)

In [34]:
next_events = codes[5:]
next_events.shape

(373861,)

In [35]:
label_windows = np.lib.stride_tricks.sliding_window_view(labels,5)

In [37]:
label_windows.shape

(373862, 5)

In [38]:
label_windows = label_windows[:-1]
label_windows.shape

(373861, 5)

In [39]:
seq_labels = (label_windows.sum(axis=1) > 0).astype(np.int8)
seq_labels.shape

(373861,)

array([0, 0, 0, ..., 0, 0, 0], dtype=int8)

In [ ]:

         # labels: [0, 1, 1, ...]
        del df  # free memory

        if len(codes) <= self.window_size:
            raise ValueError("Not enough events to form a single window.")

        # Vectorized sliding windows
        # windows shape: (N, window_size)
         # windows: (N, window_size) N: is the number of windows
          # shape (N,)
        # Compute window labels: any anomaly inside the window
        label_windows = np.lib.stride_tricks.sliding_window_view(labels, self.window_size)
        seq_labels = (label_windows.sum(axis=1) > 0).astype(np.int8)

        # Align shapes
        assert windows.shape[0] == next_events.shape[0] == seq_labels.shape[0]

In [6]:
_df = pd.read_csv(_file_path, low_memory=False)

In [7]:
_df.head()

,LineId,Content,EventId,EventTemplate,ParameterList
0,1,"line,content,labels,rules,datetime,timestamp,s...",6b1f64cf,"line,content,labels,rules,datetime,timestamp,s...",[]
1,2,"0,2022-01-24T13:30:28.294Z intranet-server sys...",062e62dd,<*> intranet-server system/system.cpu <*> host...,[]
2,3,"1,2022-01-24T13:30:38.304Z intranet-server sys...",062e62dd,<*> intranet-server system/system.cpu <*> host...,[]
3,4,"2,2022-01-24T13:31:23.305Z intranet-server sys...",ef2910eb,<*> intranet-server system/system.cpu <*> host...,[]
4,5,"3,2022-01-24T13:32:08.304Z intranet-server sys...",ef2910eb,<*> intranet-server system/system.cpu <*> host...,[]


In [15]:
!pip install logadu

Defaulting to user installation because normal site-packages is not writeable
